### ISSUE TITLE
FF4J Security problem

### ISSUE THREAD

**Issue by abuinteam** [ff4j/ff4j#264]
Hi,

I enabled spring security (basic user name and password) to access my admin console and rest api. All working good if I access my admin url or rest api in the browser or postman. Security is enabled and working fine.

But in my application I am using the below configuration,,

ff4j = new FF4j();           
ff4j.setFeatureStore(new FeatureStoreHttp("http://localhost:9081/api/ff4j","FF4J","XXX"));
ff4j.setPropertiesStore(new PropertyStoreHttp("http://localhost:9081/api/ff4j","FF4J","XXX"));

But I am getting the below error

javax.servlet.ServletException: java.lang.IllegalArgumentException: Cannot parse json as Feature HTTP Status 401 - Full authentication is required to access this resource

	at org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:286)
	at org.apache.struts.action.ActionServlet.process(ActionServlet.java:1913)
	at org.apache.struts.action.ActionServlet.doGet(ActionServlet.java:449)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:575)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at com.ibm.ws.webcontainer.servlet.ServletWrapper.service(ServletWrapper.java:1274)
	at [internal classes]
Caused by: java.lang.IllegalArgumentException: Cannot parse json as Feature HTTP Status 401 - Full authentication is required to access this resource

My username and password are correct

**Comment by clun** [comment]
There are 3 implementations of the REST API (do not ask me why jersey1x, jersey2x and spring-mvc.

I am pretty sure that the issue is on the SpringMVC implementation (part of Spring-boot-starter). Let me reproduce the issue. It seems that the JSON is not formatted as expected.

**Comment by abuinteam** [comment]
Thanks you for helping. Yes I am using springbootstarter as my admin console and rest API.

**Comment by clun** [comment]
I noticed different things so far: 

- When you use Spring-boot-web-api the API the security mechanism create is never enabled, even when putting authentication flag to "true" in the `ApiConfig` bean. In other implementation of the REST API (jersey1x, 2x) I put a HTTP filter evaluating keys in the header like - https://github.com/clun/ff4j/blob/master/ff4j-webapi-jersey2x/src/main/java/org/ff4j/web/api/security/FF4jAuthenticationFilter.java#L76-L78

- You tell you secured both admin servlet and API spring security. It is probably through you own HTTP Filter and settings. When security is enabled I think i used correct header syntax Authorization Basic ecoded user/password but will double check. I smell prototype is required here
![image](https://user-images.githubusercontent.com/726536/33372817-a01108f6-d4ff-11e7-9bf4-05b9f2ec5ec3.png)

Which REST API implementation do you used ? Come back to you .. and then final will be able to release 1.7

**Comment by clun** [comment]
Ok, I now reproduced the Issue. 

1. I setup a `WebSecurityConfigurerAdapter` with `anyRequest().authenticated()` 
2. API is reachable through test client AND browser but not with `new FeatureStoreHttp("http://localhost:9081/api/ff4j","userName","password"));`

Still under investigation but several modifications will  occured : 
- Errors will be better handle in FeatureStoreHttp (Jersey2x) to get correct HTTP CODES 
- Correct requests in FeatureStoreHttps
- Implement subclasses for `WebSecurityConfigurerAdapter` initialized through `APIConfig` in spring-boot-web-api

Stay tuned

**Comment by clun** [comment]
Done. You may have a look here:
https://github.com/clun/ff4j-samples/tree/master/ff4j-sample-springboot

**Comment by clun** [comment]
Part of 1.7

**Comment by abuinteam** [comment]
Hi Clun.

This is not working. The below is my analysis result,

In my client project I am using **ff4j-webapi-jersey1x-1.7.jar** for FeatureStoreHttp and PropertyStoreHttp. If my rest service is not password protected yes then it is working fine. But if it is password protected then I am getting the same exception. I am pretty sure on this.

aused by: org.ff4j.exception.FeatureAccessException: Cannot check existence of feature, an HTTP error 401 occured : sun.net.www.protocol.http.HttpURLConnection$HttpInputStream@36227829
	at org.ff4j.web.jersey1.store.FeatureStoreHttp.exist(FeatureStoreHttp.java:233)
	at org.ff4j.audit.proxy.FeatureStoreAuditProxy.exist(FeatureStoreAuditProxy.java:207)
	at org.ff4j.FF4j.exist(FF4j.java:414)
	at org.ff4j.web.taglib.AbstractFeatureTag.doStartTag(AbstractFeatureTag.java:84)
	at com.ibm._jsp._menuTree._jspService(_menuTree.java:241)
	at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:101)
	at [internal classes]
	at com.ibm._jsp._overviewContents._jspService(_overviewContents.java:127)
	at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:101)
	at [internal classes]
	at com.ibm._jsp._template._jspService(_template.java:158)
	at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:101)
	at [internal classes]
	at com.ibm._jsp._overview._jspService(_overview.java:105)
	at com.ibm.ws.jsp.runtime.HttpJspBase.service(HttpJspBase.java:101)
	at [internal classes]
	at org.apache.struts.chain.commands.servlet.PerformForward.handleAsForward(PerformForward.java:113)
	at org.apache.struts.chain.commands.servlet.PerformForward.perform(PerformForward.java:96)
	at org.apache.struts.chain.commands.AbstractPerformForward.execute(AbstractPerformForward.java:54)
	at org.apache.struts.chain.commands.ActionCommandBase.execute(ActionCommandBase.java:51)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at org.apache.commons.chain.generic.LookupCommand.execute(LookupCommand.java:305)
	at org.apache.commons.chain.impl.ChainBase.execute(ChainBase.java:191)
	at org.apache.struts.chain.ComposableRequestProcessor.process(ComposableRequestProcessor.java:283)
	... 6 more


But this is not happening with **ff4j-webapi-jersey2x-1.7.jar** for FeatureStoreHttp and PropertyStoreHttp. But unfortunately in order to use ff4j-webapi-jersey2x-1.7.jar our project should be in Java 1.8 version but we are pretty old stack and I cant use it.

I hope whatever the fix you have done for Jersey2x if that is done in Jersey1x that would be really great.

Thanks and waiting for your response.

**Comment by clun** [comment]
Well, ... I fixed both `ff4j-webapi-jersey2x-1.7.jar` and spring boot implementations so let do this for  ` ff4j-webapi-jersey1x-1.7.jar` 

Please note for incoming ff4j2x java8 will be a prerequisite :)  (but, well as so much work may time to be released).

**Comment by abuinteam** [comment]
Thank you Clun. If you could guid me on this I can fix this too.

**Comment by abuinteam** [comment]
Hello Clun,

Any update on this one?

**Comment by abuinteam** [comment]
Hello,

Checking to see any fix for ff4j-webapi-jersey1x-1.7.jar

**Comment by clun** [comment]
jersey1x is getting so old..

**Comment by abuinteam** [comment]
Agree. But unfortunately migrating jersey 1.0 to 2.0 requires some time from our side. In light of this if it is a simple fix from ff4j side that would benefit people who are using legacy stack.
