### ISSUE TITLE
issue while configuring audit event repository for ff4j 

### ISSUE THREAD

**Issue by manoharjangity** [ff4j/ff4j#389]
How do I setup audit feature for this configuration? I tried to add below to set audit event repository, but failed with error:

```xml
<bean id="ff4j" class="org.ff4j.FF4j">
	<property name="featureStore" ref="featureStore" /> 
	<property name="eventRepository" ref="eventRepository" /> 
</bean>

<bean id="featureStore" class="org.ff4j.store.JdbcFeatureStore" >
	<property name="dataSource" ref="dataSource" />
</bean>

<bean id="eventRepository" class="org.ff4j.audit.repository.JdbcEventRepository" >
	<property name="dataSource" ref="dataSource" />
</bean>
<!--  FF4J Configuration - Ends -->
```

Logs:
```
09:44:09,297 ERROR [stderr] (ServerService Thread Pool -- 71) org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ff4j' defined in class path resource [applicationContext-jndiDataSource.xml]: Cannot resolve reference to bean 'eventRepository' while setting bean property 'eventRepository'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'eventRepository' defined in class path resource [applicationContext-jndiDataSource.xml]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.ff4j.audit.repository.JdbcEventRepository]: No default constructor found; nested exception is java.lang.NoSuchMethodException: org.ff4j.audit.repository.JdbcEventRepository.()
09:44:09,300 ERROR [stderr] (ServerService Thread Pool -- 71) at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:359)
09:44:09,302 ERROR [stderr] (ServerService Thread Pool -- 71) at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveValueIfNecessary(BeanDefinitionValueResolver.java:108)
09:44:09,304 ERROR [stderr] (ServerService Thread Pool -- 71) at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyPropertyValues(AbstractAutowireCapableBeanFactory.java:1533)
```

**Comment by clun** [comment]
Poke @manoharjangity sorry for the late response. 

Did you make it work by now ? The issue is the class `JdbcEventRepository` expect the Datasource in the constructor... my bad.  https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/main/java/org/ff4j/audit/repository/JdbcEventRepository.java#L77

You can either use `constructor-arg` or annotation based Spring or use next version 1.8.5
<constructor-arg index="0" type="java.lang.String" value=""/>
