### ISSUE TITLE
NullPointerException while setting AWS DynamoDB as a feature store

### ISSUE THREAD

**Issue by rahuldaskar** [ff4j/ff4j#416]
Hello,

I am trying AWS DynamoDB as a feature store. I am using FF4J version 1.8.6 along with the same version of ff4j-store-aws-dynamodb. My AWS SDK version is 1.11.374.

Below is how I am setting the feature store-

`FF4j ff4j = new FF4j();
 ff4j.setFeatureStore(new FeatureStoreDynamoDB(ddbClient));`

which throws below-

`
Caused by: java.lang.NullPointerException
	at org.ff4j.dynamodb.feature.FeatureDynamoDBClient.createTable(FeatureDynamoDBClient.java:216)
	at org.ff4j.dynamodb.feature.FeatureStoreDynamoDB.createSchema(FeatureStoreDynamoDB.java:267)
	at org.ff4j.dynamodb.feature.FeatureStoreDynamoDB.initStore(FeatureStoreDynamoDB.java:390)
	at org.ff4j.dynamodb.feature.FeatureStoreDynamoDB.<init>(FeatureStoreDynamoDB.java:157)
	at org.ff4j.dynamodb.feature.FeatureStoreDynamoDB.<init>(FeatureStoreDynamoDB.java:145)
	at com.actimize.xsight.featuretoggles.configs.FF4JTestConfig.getFF4J(FF4JTestConfig.java:21)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)`

As it is failing @ _FeatureDynamoDBClient.java:216_
`if (billingMode.equals(BillingMode.PROVISIONED)) {`
It seems billingMode is null. When I further checked code, billingMode is initialized along with other config inside from _protected void loadProperties(Properties prop)_ (Line 196)

But I couldn't get from where this is called so that all the configs are initialized. Though I am not explicitly setting any config so I suppose it should work with default configs. Am I missing something here?

By the way, I get the similar error when I try to create only property store.
`
Caused by: java.lang.NullPointerException
	at org.ff4j.dynamodb.property.PropertyDynamoDBClient.createTable(PropertyDynamoDBClient.java:141)
	at org.ff4j.dynamodb.property.PropertyStoreDynamoDB.createSchema(PropertyStoreDynamoDB.java:231)
	at org.ff4j.dynamodb.property.PropertyStoreDynamoDB.initStore(PropertyStoreDynamoDB.java:248)
	at org.ff4j.dynamodb.property.PropertyStoreDynamoDB.<init>(PropertyStoreDynamoDB.java:132)
	at org.ff4j.dynamodb.property.PropertyStoreDynamoDB.<init>(PropertyStoreDynamoDB.java:120)`

Please guide.

**Comment by clun** [comment]
Hi,

I confirm the diagnostic (did not implement this class myself), `billingMode` is here indeed null. 

**Investigating the nest calls:**
1. new FeatureStoreDynamoDB(ddbClient)
2. got to FeatureStoreDynamoDB(AmazonDynamoDB amazonDynamoDB, String tableName)
3. go to initStore(AmazonDynamoDB amazonDynamoDB, String tableName)
4. go to FeatureDynamoDBClient(AmazonDynamoDB amazonDynamoDB, String tableName)
5. go to DynamoDBClient(AmazonDynamoDB amazonDynamoDB, String tableName)
6. loadPropertiesIfExist();
7. loadProperties(prop);

#7 is invoked only if the file `ff4j-dynamodb.properties` is found in the classPath. 
https://github.com/ff4j/ff4j/blob/master/ff4j-store-aws-dynamodb/src/main/java/org/ff4j/dynamodb/DynamoDBClient.java#L88

Also seems the Billing Mode default value is `PROVISIONED` 

**Quick solutions:**
- add the file `ff4j-dynamodb.properties` in your classpath

**Evolution for FF4j**
- set a default value for BillingMode to PROVISIONNED
- change code from value.equals(constant) to constant.equals(value) in the code

**Comment by rahuldaskar** [comment]
Thanks @clun for reply!

I added ff4j-dynamodb.properties with below contents in the classpath and it worked!
`
## Properties DDB Table
ff4j.store.dynamodb.property.table.name=ff4j-properties
ff4j.store.dynamodb.property.table.billing=PROVISIONED
ff4j.store.dynamodb.property.table.billing.rcu=5
ff4j.store.dynamodb.property.table.billing.wcu=5

## Features DDB Table
ff4j.store.dynamodb.feature.table.name=ff4j-features
ff4j.store.dynamodb.feature.table.billing=PROVISIONED
ff4j.store.dynamodb.feature.table.billing.rcu=5
ff4j.store.dynamodb.feature.table.billing.wcu=5
`
Actually, I was referring to https://github.com/ff4j/ff4j/wiki/Store-Technologies#aws-dynamodb and it doesn't have any reference about _ff4j-dynamodb.properties_ That's why I missed adding the same in classpath.

**Comment by jeromevdl** [comment]
I've created the pull request: https://github.com/ff4j/ff4j/pull/417

And modified the documentation: https://github.com/ff4j/ff4j/wiki/Store-Technologies#aws-dynamodb

**Comment by clun** [comment]
Thank ! Finishing a (cool) evolution (load features from `Yaml` opening integrations with `application.yaml` or configMAP and I ship `1.8.7`

**Comment by rahuldaskar** [comment]
Thanks @jeromevdl !
