### ISSUE TITLE
Help me fixing my project with Microsoft SQL Server ? Got error `operand type clash datetime2 is incompatible with timestamp`

### ISSUE THREAD

**Issue by mageshbabu-spg** [ff4j/ff4j#456]
My Project Structure:
Spring Boot + DB : MS SQL + FF4j (FeatureStoreSpringJdbc)

Created the table schema as below url
https://github.com/ff4j/ff4j/blob/master/ff4j-core/src/main/resources/schema-ddl.sql

Getting "operand type clash datetime2 is incompatible with timestamp" Exception when accessing "/api/ff4j" rest api
Is there any way to resolve this issue

Exception StackTrace:
org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [SELECT count(EVT_UUID) as NB, EVT_NAME FROM FF4J_AUDIT WHERE (EVT_TYPE LIKE 'feature') AND (EVT_ACTION LIKE 'checkOn') AND (EVT_TIME> ?) AND (EVT_TIME< ?) GROUP BY EVT_NAME]; SQL state [S0002]; error code [206]; Operand type clash: datetime2 is incompatible with timestamp; nested exception is com.microsoft.sqlserver.jdbc.SQLServerException: Operand type clash: datetime2 is incompatible with timestamp

at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)

at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)

at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)

at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)

at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)

at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)

at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)

at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:712)

at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:768)

at org.ff4j.springjdbc.store.EventRepositorySpringJdbc.computeHitCount(EventRepositorySpringJdbc.java:151)

at org.ff4j.springjdbc.store.EventRepositorySpringJdbc.getFeatureUsageHitCount(EventRepositorySpringJdbc.java:119)

at org.ff4j.audit.repository.AbstractEventRepository.getFeatureUsagePieChart(AbstractEventRepository.java:58)

at org.ff4j.services.domain.EventRepositoryApiBean.initialize(EventRepositoryApiBean.kt:55)

at org.ff4j.services.domain.EventRepositoryApiBean.<init>(EventRepositoryApiBean.kt:46)

at org.ff4j.services.domain.FF4jStatusApiBean.<init>(FF4jStatusApiBean.kt:66)

at org.ff4j.services.FF4jServices.getStatus(FF4jServices.kt:40)

at org.ff4j.spring.boot.web.api.resources.FF4jResource.getStatus(FF4jResource.kt:55)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)

at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)

**Comment by clun** [comment]
Hello,

There is definitively something off with your config. You talk me about Mysql but your error message leverage on Microsoft server `com.microsoft.sqlserver.jdbc.SQLServerException:` You have an invalid import somewhere.

You should check this sample
https://github.com/ff4j/ff4j-samples/tree/master/spring-boot-2x/ff4j-sample-springboot2x-jdbc-postgres

and change from postgres to MYsql

```xml
 <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>8.0.16</version>
        </dependency>
```

```java
  BasicDataSource dataSource = new BasicDataSource();
            dataSource.setDriverClassName("com.mysql.jdbc.Driver");
            dataSource.setUrl("jdbc:mysql://localhost:3306/ff4j_v1");
            dataSource.setUsername("root");
            dataSource.setPassword("docu1");
            dataSource.setConnectionProperties("useUnicode=yes;characterEncoding=UTF-8;");

            ff4j.setFeatureStore(new JdbcFeatureStore(dataSource));
            ff4j.setPropertiesStore(new JdbcPropertyStore(dataSource));
            ff4j.setEventRepository(new JdbcEventRepository(dataSource));
```

**Comment by clun** [comment]
Microsoft SQL Server using dedicated type it seems. Please change the DDL as stated here 
https://www.qvera.com/kb/index.php/1427/operand-datetime2-incompatible-timestamp-timestamp-datatype

Would be nice to have a pull request with `schema-ddl-mssql` I don't have on my MAC to test.

**Comment by clun** [comment]
any update @mageshbabu-spg ?

**Comment by mageshbabu-spg** [comment]
Hi @clun ,
Issue fixed after changed to datetime type

**Comment by clun** [comment]
Alright perfect, will close the ticket with the description as support. I think this is what the file look like for MS SQL

```sql
-- Main Table to store Features
CREATE TABLE FF4J_FEATURES (
  "FEAT_UID"     	VARCHAR(100),
  "ENABLE"  		INTEGER NOT NULL,
  "DESCRIPTION" 	VARCHAR(1000),
  "STRATEGY"		VARCHAR(1000),
  "EXPRESSION"	    VARCHAR(255),
  "GROUPNAME"		VARCHAR(100),
  PRIMARY KEY("FEAT_UID")
);

-- Roles to store ACL, FK to main table
CREATE TABLE FF4J_ROLES (
  "FEAT_UID"     VARCHAR(100) REFERENCES FF4J_FEATURES("FEAT_UID"),
  "ROLE_NAME"    VARCHAR(100),
  PRIMARY KEY("FEAT_UID", "ROLE_NAME")
);

-- Feature Internal Custom Properties
CREATE TABLE FF4J_CUSTOM_PROPERTIES (
  "PROPERTY_ID"  VARCHAR(100) NOT NULL,
  "CLAZZ" 		 VARCHAR(255) NOT NULL,
  "CURRENTVALUE" VARCHAR(255),
  "FIXEDVALUES"	 VARCHAR(1000),
  "DESCRIPTION"	 VARCHAR(1000),
  "FEAT_UID"     VARCHAR(100) REFERENCES FF4J_FEATURES("FEAT_UID"),
  PRIMARY KEY("PROPERTY_ID", "FEAT_UID")
);

-- @PropertyStore (edit general properties)
CREATE TABLE FF4J_PROPERTIES (
  "PROPERTY_ID"  VARCHAR(100) NOT NULL,
  "CLAZZ" 		 VARCHAR(255) NOT NULL,
  "CURRENTVALUE" VARCHAR(255),
  "FIXEDVALUES"	 VARCHAR(1000),
  "DESCRIPTION"	 VARCHAR(1000),
  PRIMARY KEY("PROPERTY_ID")
);

-- @see JdbcEventRepository (audit event)
CREATE TABLE FF4J_AUDIT (
  "EVT_UUID" 	 VARCHAR(40)  NOT NULL,
  "EVT_TIME" 	 DATETIME2 	  NOT NULL,
  "EVT_TYPE" 	 VARCHAR(30)  NOT NULL,
  "EVT_NAME" 	 VARCHAR(100)  NOT NULL,
  "EVT_ACTION" 	 VARCHAR(100)  NOT NULL,
  "EVT_HOSTNAME" VARCHAR(100)  NOT NULL,
  "EVT_SOURCE" 	 VARCHAR(30)  NOT NULL,
  "EVT_DURATION" INTEGER,
  "EVT_USER" 	 VARCHAR(30),
  "EVT_VALUE" 	 VARCHAR(100),
  "EVT_KEYS" 	 VARCHAR(255),
  PRIMARY KEY("EVT_UUID", "EVT_TIME")
);
```
