### ISSUE TITLE
Unable to use ff4j web console in quarkus application: Caused by: java.lang.ClassNotFoundException: org.acme.MyFF4jProvider

### ISSUE THREAD

**Issue by franden** [ff4j/ff4j#487]
If I try to use ff4j web console in a quarkus application, I get following Exception on startup of the FF4jDispatcherServlet that the class of my FF4jProvider is not known:
```
Caused by: java.lang.ClassNotFoundException: org.acme.MyFF4jProvider
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:428)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:378)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:315)
        at org.ff4j.web.FF4jServlet.initializeFF4J(FF4jServlet.java:152)
        ... 29 more
```

The reason is  this line:
https://github.com/ff4j/ff4j/blob/f3c07b49deabd04caef8b0f3a491ab3ae514ca36/ff4j-web/src/main/java/org/ff4j/web/FF4jServlet.java#L152

As described [here](https://github.com/quarkusio/quarkus/issues/2809): "Class.forName() without a CL is often problematic."

Please change this line to use the current classlaoder:  Class<?> c = Thread.currentThread().getContextClassLoader().loadClass(className);

**Comment by clun** [comment]
You are right will work on it over the week-end would be great to have a quarkus sample in the pool

**Comment by franden** [comment]
Similar Issue happens if custom flipping strategy is used. In this case the custom class can not be loaded (ClassNotFoundException): https://github.com/ff4j/ff4j/blob/a31cb8caf8b8c4874fcd6bb64893f4f50919af3c/ff4j-core/src/main/java/org/ff4j/utils/MappingUtil.java#L183

it could be changed to: 
```Class<FlippingStrategy> clazz = (Class<FlippingStrategy>) (classLoader == null ? Thread.currentThread().getContextClassLoader().loadClass(className) : classLoader.loadClass(className));```

Currently I am using: MappingUtil.setClassLoader(Thread.currentThread().getContextClassLoader()); as workaround

**Comment by franden** [comment]
I guess the similar issue will happen everywhere where Class.forName(className) is used to load custom code from
e.g: https://github.com/ff4j/ff4j/blob/a31cb8caf8b8c4874fcd6bb64893f4f50919af3c/ff4j-core/src/main/java/org/ff4j/property/util/PropertyFactory.java#L163

![image](https://user-images.githubusercontent.com/20822716/107516533-d8c0e800-6bac-11eb-95c9-f3819fa89057.png)

**Comment by clun** [comment]
ack
