### ISSUE TITLE
[Bug]Accessing the rest api?

### ISSUE THREAD

**Issue by JangoCG** [ff4j/ff4j#709]
Hi,
with version 2.x.x how can I access the rest api? and the swagger? the docs are outdated for this.

Best Regards

Cengiz

**Comment by allantl** [comment]
I have the same question. How do I enable ff4j swagger? The `EnableFF4jSwagger` is not available anymore in the latest version.

**Comment by clun** [comment]
Are you using the Spring Boot Starter ? 

It is defined in `application.yaml` now..set by configuration rather than code 
https://github.com/ff4j/ff4j-samples/blob/master/ff4j-spring-boot-samples/ff4j-spring-boot-starter-webflux-sample/src/main/resources/application.yml

**Comment by JangoCG** [comment]
The sample you linked cannot be installed, because the dependency ff4j-spring-boot-starter-webflux does not exist.
But yes I am trying to use it in my spring boot service.

These are the dependencies I use in my project

`spring-boot-starter-data-jpa = { module = "org.springframework.boot:spring-boot-starter-data-jpa" }
spring-cloud-starter-openfeign = { module = "org.springframework.cloud:spring-cloud-starter-openfeign" }
spring-hateoas = { module = "org.springframework.hateoas:spring-hateoas" }
spring-data-commons = { module = "org.springframework.data:spring-data-commons" }
spring-cloud-stream-binder-kafka = { module = "org.springframework.cloud:spring-cloud-stream-binder-kafka" }
spring-cloud-stream-binder-kafka-streams = { module = "org.springframework.cloud:spring-cloud-stream-binder-kafka-streams" }
springdoc-hateoas = { module = "org.springdoc:springdoc-openapi-hateoas" }
mapstruct-processor = { module = "org.mapstruct:mapstruct-processor" }
hibernate-validator = { module = "org.hibernate.validator:hibernate-validator" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
resilence4j = { module = "io.github.resilience4j:resilience4j-spring-boot2" }
postgres = { module = "org.postgresql:postgresql" }
ff4j-spring-boot-starter = { module = "org.ff4j:ff4j-spring-boot-starter-parent", version.ref = "removed-ff4j-spring-boot" }
ff4j-web = { module = "org.ff4j:ff4j-web", version.ref = "removed-ff4j" }
ff4j-store-springjdbc = { module = "org.ff4j:ff4j-store-springjdbc", version.ref = "removed-ff4j" }
ff4j-security-spring = { module = "org.ff4j:ff4j-security-spring", version.ref = "removed-ff4j" }
`

Enabling the fields in the application.yml as you provided does not work. I just get the standard spring boot error page

**Comment by clun** [comment]
We released the support of Spring Boot 3x today (previously it was 2x only). 
https://repo1.maven.org/maven2/org/ff4j/ff4j-spring-boot-starter-webflux/2.0.0-RC1/

Could you please retry today ?

**Comment by JangoCG** [comment]
Ah I see.  Thank you for your reply. Yesterday I noticed that spring-boot-starter is wrong and that It works when I use spring-boot-starter-web-mvc with the 2.0.0 Snapshot which I've build myself.
However when I use the 2.0.0-RC1 I get the following exception

`java.lang.IllegalStateException: Duplicate key ff4j (attempted merging values org.springdoc.webmvc.api.OpenApiWebMvcResource@6b861a26 and org.springdoc.webmvc.api.OpenApiWebMvcResource@3db32d5)
	at org.springdoc.webmvc.api.MultipleOpenApiResource.afterPropertiesSet(MultipleOpenApiResource.java:137) [9 skipped]
	at com.daimler.trucks.customerportal.feature.FeatureServiceApplication.main(FeatureServiceApplication.java:19) [17 skipped]
	... 16 common frames omitted
Wrapped by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'multipleOpenApiResource' defined in class path resource [org/springdoc/webmvc/core/configuration/MultipleOpenApiSupportConfiguration.class]: Duplicate key ff4j (attempted merging values org.springdoc.webmvc.api.OpenApiWebMvcResource@6b861a26 and org.springdoc.webmvc.api.OpenApiWebMvcResource@3db32d5)
	at com.daimler.trucks.customerportal.feature.FeatureServiceApplication.main(FeatureServiceApplication.java:19) [16 skipped]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'multipleOpenApiResource' defined in class path resource [org/springdoc/webmvc/core/configuration/MultipleOpenApiSupportConfiguration.class]: Duplicate key ff4j (attempted merging values org.springdoc.webmvc.api.OpenApiWebMvcResource@6b861a26 and org.springdoc.webmvc.api.OpenApiWebMvcResource@3db32d5)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1770)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:941)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:733)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:435)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1294)
	at com.daimler.trucks.customerportal.feature.FeatureServiceApplication.main(FeatureServiceApplication.java:19)
Caused by: java.lang.IllegalStateException: Duplicate key ff4j (attempted merging values org.springdoc.webmvc.api.OpenApiWebMvcResource@6b861a26 and org.springdoc.webmvc.api.OpenApiWebMvcResource@3db32d5)
	at java.base/java.util.stream.Collectors.duplicateKeyException(Collectors.java:135)
	at java.base/java.util.stream.Collectors.lambda$uniqKeysMapAccumulator$1(Collectors.java:182)
	at java.base/java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.springdoc.webmvc.api.MultipleOpenApiResource.afterPropertiesSet(MultipleOpenApiResource.java:137)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1816)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766)
	... 16 more`

**Comment by JangoCG** [comment]
Update
I noticed you also just pushed new commits to the sample repo where you updated the yaml to configure spring doc. With those changes my rest api and swagger works.

Swagger is reachable under the following URL for me
http://localhost:8083/swagger-ui/index.html#/
